config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'


Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources:shows do
    member do
        post :add_to_favorites
        delete :remove_from_favorites
    end
  end
  get "/favorites", to: "shows#favorites_index", as: "favorites"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
    has_many:shows, dependent: :destroy

    validates :name, presence: true
    
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/show.rb
class Show < ApplicationRecord
    belongs_to:channel

    acts_as_favoritable

    self.per_page = 5

    def self.search(search)
        joins(:channel).where('shows.name like (?) OR channels.name like (?)',"%#{search}%","%#{search}%")
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_favoritor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
    def index
    end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    before_action :authenticate_user!, only: :show
    before_action :get_show, only: [:add_to_favorites, :remove_from_favorites]
    def index
        # @shows = Show.all
        if params[:search]
            flash[:success] = "Search results"
            @shows = Show.search(params[:search].strip).order("created_at DESC").paginate(page: params[:page])
        else
            @shows = Show.all.order("created_at DESC").paginate(page: params[:page])
        end
    end

    def show
        @show = Show.find(params[:id])
        # ShowNotificationJob.perform_async(@show.name)
        # ShowNotificationMailer.notification(@show, current_user).deliver_later
    end

    def add_to_favorites
        if current_user.favorite(@show)
            flash[:success] = "Marked as favorite"
        else
            flash[:alert] = "Can not mark favorite. please try again later."
        end
        redirect_back fallback_location: shows_path

    end

    def remove_from_favorites
        if current_user.unfavorite(@show)
            flash[:success] = "Removed from your favorites"
        else
            flash[:alert] = "Can not removed from favorites. please try again later."
        end
        redirect_back fallback_location: shows_path
    end

    def favorites_index
        @shows = current_user.all_favorited
    end

    private
    def get_show
        @show = Show.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

Dear, <%= current_user.email ? current_user.email : ""  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TVSHOW</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/shared/header' %>
  <div class="container">
      <% if notice %>
       <p class="alert alert-primary"><%= notice %></p>
       <% end %>
       <% if alert %>
       <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= render 'layouts/shared/flash' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
      <%= value %>
      
    </div>
  <% end %>
  

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="">TvShow</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "Shows", shows_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Favourites", favorites_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <b><%= link_to "logout", destroy_user_session_path, method: :delete, data: { turbo_method: :delete}, class: 'nav-link'  %></b>
        </li>
        <li class="nav-item">
        <b><%= link_to "Profile", edit_user_registration_path, class: 'nav-link'  %></b>
      </li>
        <% else %>
        <li class="nav-item">
          <b><%= link_to "logIn", new_user_session_path, class: 'nav-link'  %></b>
        </li>
        <li class="nav-item">
          <b><%= link_to "Register", new_user_registration_path, class: 'nav-link'  %></b>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shows/_search.html.erb
<%= form_tag(shows_path, :method => "get", class: "d-flex") do %>  
    <%= text_field_tag :search, params[:search], placeholder: "search show, channel", class: "form-control me-2" %>
    <button class="btn btn-outline-success" type="submit">Search</button>
  <% end %>

app/views/shows/favorites_index.html.erb
<h2>Your Favorites</h2>
<div class="row">
    <% @shows.each do |show| %>
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title"><%= show.name %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= show.start_time.to_s(:time) %> To <%= show.end_time.to_s(:time) %></h6>
                <!--p class="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p-->
                
                <%= link_to "View Details", show_path(show), class: "card-link" %>
                <% if current_user.favorited?(show) %>
                <%= link_to "Remove from favourites", remove_from_favorites_show_path(show), method: :delete, data: { turbo_method: :delete}, class: "btn btn-danger m-2 text-black" %>
                <% else %>
                <%= form_tag(add_to_favorites_show_path(show), :method => "post") do %>
                    <button type="submit" class="btn btn-primary" >Mark As Favorite</button>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/shows/index.html.erb
<h2>Available shows</h2>
<div class="col-md-4">
<%= render 'search' %>
</div>
<br/>
<div class="row">
    <% @shows.each do |show| %>
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title"><%= show.name %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= show.start_time.to_s(:time) %> To <%= show.end_time.to_s(:time) %></h6>
                <!--p class="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p-->
                
                <%= link_to "View Details", show_path(show), class: "card-link" %>
                <% if user_signed_in? %>
                <% if current_user.favorited?(show) %>
                <%= link_to "Remove from favourites", remove_from_favorites_show_path(show), method: :delete, data: { turbo_method: :delete}, class: "btn btn-danger m-2 text-black" %>
                <% else %>
                <%= form_tag(add_to_favorites_show_path(show), :method => "post") do %>
                    <button type="submit" class="btn btn-primary" >Mark As Favorite</button>
                <% end %>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
    <%= will_paginate @shows %>
</div>

app/views/shows/show.html.erb
<h2>Show details</h2>
<div class="card" style="width: 18rem;">
<div class="card-body">
    <h5 class="card-title"><%= @show.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @show.start_time.to_s(:time) %> To <%= @show.end_time.to_s(:time) %></h6>
    <p class="card-text">Channel name : <%= @show.channel&.name %></p>
    <% if current_user.favorited?(@show) %>
    <%= link_to "Remove from favourites", remove_from_favorites_show_path(@show), method: :delete, data: { turbo_method: :delete}, class: "btn btn-danger m-2 text-black" %>
    <% else %>
    <%= form_tag(add_to_favorites_show_path(@show), :method => "post") do %>
        <button type="submit" class="btn btn-primary" >Mark As Favorite</button>
    <% end %>
    <% end %>
    <!--a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a-->
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>